/* eslint-disable max-len */
// eslint-disable-next-line import/no-anonymous-default-export

function getRandomNumber(min: number, max: number): number {
  if (min >= max) {
    throw new Error('Min value must be less than max value.');
  }
  return Math.floor(Math.random() * (max - min + 1)) + min;
}
export default {
  sentimentScore: getRandomNumber(20, 100),
  attentionScore: getRandomNumber(20, 100),
  sentiments: [
    {
      id: '6512f01216c3b12f2395ee01',
      text: 'Labore amet irure proident voluptate. Eiusmod ad exercitation tempor ullamco Lorem laborum irure veniam id eu enim nostrud. Deserunt fugiat ea reprehenderit do ullamco fugiat sunt duis. Ex minim officia ut aliquip in enim consequat ex est laboris minim. In nulla eiusmod id ipsum nulla laborum cillum commodo duis fugiat adipisicing officia.',
      labels: ['Frustration', 'Negative'],
      created_at: '2023-09-15T19:50:25.776Z',
      annotations: [
        {
          id: '6512f0124bfabecbc1015be1',
          text: 'Ea qui quis dolor amet officia laboris ad. Sit laboris magna consectetur culpa nostrud sunt in. Adipisicing ut nostrud cupidatat quis reprehenderit mollit occaecat Lorem pariatur occaecat occaecat sit. Excepteur consectetur in ex esse exercitation nostrud excepteur est labore excepteur.',
          comments: [
            {
              id: '6512f012e6e242d19509dbd7',
              name: 'Dollie Rivera',
              text: 'Laboris duis aliquip eiusmod fugiat velit irure mollit. Voluptate adipisicing aliquip sunt sit proident ad voluptate nisi ullamco et aliqua. Eu excepteur non ea quis amet eiusmod velit adipisicing enim.',
              userId: '6512f01239aa8b16d5e1307e',
              isActive: true,
              created_at: '2023-09-12T05:15:41.950Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
            {
              id: '6512f012223b520e9a3975f3',
              name: 'Maura Dorsey',
              text: 'Commodo eu qui in elit nostrud in. Irure veniam exercitation elit eu incididunt cillum sit. Culpa adipisicing proident veniam quis do dolore sunt nulla est aliquip.',
              userId: '6512f012a9cfc04c3c1b3418',
              isActive: true,
              created_at: '2023-09-13T19:55:21.705Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
            {
              id: '6512f0124fce666337616532',
              name: 'Pace Jacobson',
              text: 'Minim labore labore id cillum ex minim nostrud. Irure nisi exercitation enim anim. Cillum aute commodo sint deserunt.',
              userId: '6512f01216b6464159097337',
              isActive: true,
              created_at: '2023-09-21T05:52:20.490Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
          ],
          created_at: '2023-09-10T02:59:51.237Z',
        },
        {
          id: '6512f012dbedd6b8b870c324',
          text: 'Aliqua incididunt velit reprehenderit quis elit in culpa culpa. Fugiat ad eu enim est et cillum incididunt officia occaecat. Occaecat sit occaecat culpa occaecat anim ipsum cillum dolor labore enim esse excepteur. Anim et labore pariatur tempor elit.',
          comments: [
            {
              id: '6512f012289f256e1b3992f2',
              name: 'Flowers Serrano',
              text: 'Laborum id consectetur irure officia esse veniam consectetur proident amet consectetur anim et. Mollit ad dolor sunt dolor adipisicing exercitation magna mollit officia sunt officia ullamco deserunt. Nulla nulla sit culpa irure non exercitation ad elit elit est magna.',
              userId: '6512f0124dd1d7ba8df17c0a',
              isActive: true,
              created_at: '2023-09-08T21:15:56.806Z',
              profileUrl: '',
            },
            {
              id: '6512f012e83589cafc6f6127',
              name: 'Mcleod Wolf',
              text: 'Fugiat non sit pariatur commodo in officia ullamco enim anim dolore incididunt incididunt non elit. Fugiat deserunt et labore excepteur in magna. Aliquip consequat ea esse et irure in incididunt consectetur mollit adipisicing velit velit.',
              userId: '6512f012a11953e9d49fc1a3',
              isActive: true,
              created_at: '2023-09-04T02:56:52.361Z',
              profileUrl: '',
            },
            {
              id: '6512f012194e27842d140df2',
              name: 'Julianne Clarke',
              text: 'In consequat exercitation ea fugiat aute cillum consectetur anim tempor sit. Est culpa nisi occaecat quis enim culpa velit minim magna labore. Aute laboris consectetur anim excepteur do veniam ad incididunt laboris labore.',
              userId: '6512f01238b6007a5fc11bb6',
              isActive: true,
              created_at: '2023-09-08T06:01:34.901Z',
              profileUrl: '',
            },
          ],
          created_at: '2023-09-02T11:08:49.677Z',
        },
        {
          id: '6512f0128b3c14641a7a409a',
          text: 'Commodo dolor officia sunt commodo aute et aliqua ut eu proident. Irure nostrud nulla fugiat mollit culpa adipisicing irure quis pariatur minim tempor ipsum ut. Mollit occaecat ad officia aute. Lorem ad proident sint qui sit ut.',
          comments: [
            {
              id: '6512f012f7d0c80a16596037',
              name: 'Lynn Klein',
              text: 'Duis amet ipsum esse officia labore sunt ex dolore fugiat. Aute proident sit commodo eu ea id eiusmod. In dolore officia laboris proident tempor ipsum.',
              userId: '6512f0128f90db45cb83c5fb',
              isActive: false,
              created_at: '2023-09-09T07:23:38.553Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
            {
              id: '6512f012b00db5e5fab884e3',
              name: 'Kelsey Mcdowell',
              text: 'Eiusmod commodo nostrud officia tempor anim ea exercitation aute pariatur qui aliqua elit ullamco minim. Sit do consequat velit voluptate tempor ut ut minim anim dolor aute. In exercitation proident est fugiat consectetur duis ullamco dolor fugiat.',
              userId: '6512f0127ad5b0bf5850788f',
              isActive: false,
              created_at: '2023-09-12T00:50:46.481Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
            {
              id: '6512f01209dfe15f4416db20',
              name: 'Harrington Merritt',
              text: 'Voluptate anim cupidatat pariatur nisi tempor nulla do id labore pariatur aute. Ea anim elit sit exercitation excepteur sit incididunt do proident veniam ex. Excepteur ullamco in velit reprehenderit.',
              userId: '6512f012ee986776ce63da83',
              isActive: false,
              created_at: '2023-09-06T19:55:35.168Z',
              profileUrl: '',
            },
          ],
          created_at: '2023-09-20T06:26:46.611Z',
        },
      ],
    },
    {
      id: '6512f01222242aa0bb0b8ba0',
      text: 'Ut amet fugiat laboris nisi ad amet voluptate. Ea consequat labore ut magna eiusmod sunt incididunt consequat commodo in. Commodo sint cupidatat id sint non cillum dolor officia consectetur sit qui ex. Esse ipsum sit magna ea minim non amet amet do aliquip laboris et ex quis. Irure laboris do proident do.',
      labels: ['Escalation Request', 'Negative', 'Frustration'],
      created_at: '2023-09-20T13:49:53.007Z',
      annotations: [
        {
          id: '6512f01205a9c49c69c86c08',
          text: 'Esse irure do quis veniam ipsum. Eu labore consectetur est consequat reprehenderit occaecat ullamco voluptate dolor reprehenderit id nostrud occaecat. Pariatur voluptate mollit ea enim do ex tempor aute ut irure reprehenderit deserunt. Cillum consectetur culpa eu officia sit culpa anim consequat fugiat laborum id.',
          comments: [
            {
              id: '6512f012725692c3338428eb',
              name: 'Karyn Snider',
              text: 'Magna qui voluptate labore reprehenderit. Dolore esse Lorem nisi anim commodo laborum elit aliquip mollit Lorem do minim dolore. Nostrud excepteur cupidatat consectetur ad anim anim minim adipisicing dolor do.',
              userId: '6512f012a16d7eb0ce95192e',
              isActive: true,
              created_at: '2023-09-05T22:28:07.906Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
            {
              id: '6512f0121c99f05bdd722029',
              name: 'Susanne Huff',
              text: 'Aliqua deserunt consectetur consectetur qui quis Lorem ut aute reprehenderit consectetur fugiat deserunt do. Sunt quis proident consectetur officia cupidatat in ea cupidatat ex minim ipsum elit. Tempor exercitation in dolore reprehenderit ex.',
              userId: '6512f012e3d63a81652295ac',
              isActive: false,
              created_at: '2023-09-06T11:18:46.911Z',
              profileUrl: '',
            },
            {
              id: '6512f0129fc12faeddaf54ca',
              name: 'Delores Ware',
              text: 'Sint magna dolor amet cupidatat. Ad est exercitation officia mollit commodo elit reprehenderit sunt nostrud reprehenderit do esse. Incididunt cillum sint dolore officia.',
              userId: '6512f0125b45276dc24d828d',
              isActive: true,
              created_at: '2023-09-18T20:49:15.276Z',
              profileUrl: '',
            },
          ],
          created_at: '2023-09-05T18:38:35.255Z',
        },
        {
          id: '6512f012a25f9fc9f9dd4fdb',
          text: 'Consectetur dolore adipisicing duis commodo id laborum labore aute. Excepteur quis ullamco reprehenderit magna occaecat exercitation irure sit do proident fugiat adipisicing. Magna reprehenderit sit dolore pariatur irure labore sit adipisicing. Commodo irure non mollit labore minim aliquip deserunt ipsum do elit ad proident ut consectetur.',
          comments: [
            {
              id: '6512f012225245c2db8439f8',
              name: 'Benton Estes',
              text: 'Nulla tempor ipsum ipsum deserunt fugiat minim in quis. Sit deserunt nostrud nisi id minim laborum adipisicing. Ea sunt eiusmod quis in cupidatat officia non.',
              userId: '6512f012d22d5e0c89fd0651',
              isActive: false,
              created_at: '2023-09-19T12:44:03.462Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
            {
              id: '6512f012b162b3d6917aef4b',
              name: 'Ophelia Young',
              text: 'Lorem elit aute non excepteur. Laborum amet adipisicing incididunt laboris aliquip. Adipisicing aute culpa exercitation mollit qui officia dolor quis cillum do.',
              userId: '6512f0129113a8c187b3d288',
              isActive: false,
              created_at: '2023-09-20T15:55:57.033Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
            {
              id: '6512f01208e887534c72d9f8',
              name: 'Glenn Holland',
              text: 'Ex esse tempor esse tempor veniam est est magna sunt non sit id irure. Excepteur ex deserunt aliqua culpa laborum pariatur enim. Id ea in est irure irure laborum aliqua proident in minim.',
              userId: '6512f012f36d6e2656153a19',
              isActive: true,
              created_at: '2023-09-09T02:04:16.691Z',
              profileUrl: '',
            },
          ],
          created_at: '2023-09-20T23:50:43.429Z',
        },
        {
          id: '6512f012e9414c35260fb729',
          text: 'Enim et eiusmod nostrud sunt officia non laborum sint id. Culpa velit irure duis nisi velit commodo eu et veniam do commodo ea. Pariatur cupidatat dolore laborum duis culpa voluptate commodo laborum ipsum aliquip. Dolor magna ex pariatur ea ipsum ut ex dolore nostrud in sint aliquip ex magna.',
          comments: [
            {
              id: '6512f012e838ba6da32434c6',
              name: 'Nicole Pacheco',
              text: 'Anim nulla reprehenderit reprehenderit laboris magna ex proident duis. Aliqua nisi culpa qui anim officia. Ex est amet ipsum duis officia et dolore.',
              userId: '6512f012d6788b4bc1e52ac8',
              isActive: false,
              created_at: '2023-09-05T02:00:40.546Z',
              profileUrl: '',
            },
            {
              id: '6512f012aabe043c22cb5847',
              name: 'Cleveland Caldwell',
              text: 'Ea ullamco aute tempor dolor ipsum adipisicing. Cupidatat ut consectetur dolor incididunt minim ullamco ut velit veniam sunt ad. Reprehenderit amet eiusmod excepteur cupidatat quis excepteur voluptate commodo cillum eu amet exercitation consectetur.',
              userId: '6512f0128fd36e7a2efe645a',
              isActive: false,
              created_at: '2023-09-04T17:08:42.401Z',
              profileUrl: '',
            },
            {
              id: '6512f012544dbaa09b4dbdea',
              name: 'Lakisha Harding',
              text: 'Dolor ut aute qui minim sint duis ad veniam. Ullamco adipisicing aute qui aute magna laborum incididunt adipisicing excepteur ullamco. Mollit esse elit magna anim.',
              userId: '6512f01290f6793b4f2d8dd4',
              isActive: false,
              created_at: '2023-09-19T15:22:51.310Z',
              profileUrl: '',
            },
          ],
          created_at: '2023-09-18T07:11:21.925Z',
        },
      ],
    },
    {
      id: '6512f012e0d79b6ba7ee26cd',
      text: 'Nulla officia sit cillum consequat qui consectetur reprehenderit aliqua anim. Aute laborum quis nulla culpa nulla. Nostrud et Lorem ullamco qui cillum enim commodo excepteur nulla. Sunt non nisi eiusmod laborum ipsum eiusmod. Dolore incididunt exercitation incididunt voluptate irure.',
      labels: ['Frustration', 'Negative'],
      created_at: '2023-09-11T02:43:42.591Z',
      annotations: [
        {
          id: '6512f0126b6bc8d92c5b2107',
          text: 'Sint esse deserunt ea id. Ut enim sunt veniam qui magna in proident amet adipisicing nostrud sunt. Incididunt do culpa occaecat et proident deserunt Lorem aliquip cillum et aliquip nulla magna qui. Ipsum aliqua deserunt reprehenderit do sunt id occaecat non cillum sint.',
          comments: [
            {
              id: '6512f0120c611c151502e803',
              name: 'Vaughn Harvey',
              text: 'Ut officia ea exercitation veniam. Excepteur est labore labore reprehenderit consequat commodo ut excepteur. Exercitation qui deserunt eiusmod esse do enim ex dolore reprehenderit labore.',
              userId: '6512f0122c0565837e98e71a',
              isActive: true,
              created_at: '2023-09-12T15:35:03.616Z',
              profileUrl: '',
            },
            {
              id: '6512f0129e53066e490ad605',
              name: 'Wiley Porter',
              text: 'Non fugiat ex culpa sit veniam. Labore minim nostrud ex exercitation excepteur aliqua id id proident. Consequat ea nostrud tempor cillum.',
              userId: '6512f012822040e8f9e921dd',
              isActive: false,
              created_at: '2023-09-09T06:39:15.883Z',
              profileUrl: '',
            },
            {
              id: '6512f0124ddaa1f7f5e59703',
              name: 'Foster Mccarthy',
              text: 'Eu labore dolore commodo tempor. Do nulla est consectetur adipisicing. Enim nostrud aute excepteur deserunt occaecat reprehenderit non amet.',
              userId: '6512f0121f3f6be3acf8ac07',
              isActive: true,
              created_at: '2023-09-16T17:50:06.706Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
          ],
          created_at: '2023-09-11T09:07:18.617Z',
        },
        {
          id: '6512f0127e0671b9c9ef3793',
          text: 'Id consequat consectetur exercitation laborum commodo. Esse duis ullamco anim velit minim Lorem laboris cupidatat. Quis et non est nisi consectetur commodo aliquip id adipisicing anim. Laboris fugiat sint adipisicing magna commodo.',
          comments: [
            {
              id: '6512f012bb9144923ef12b24',
              name: 'Bessie Campbell',
              text: 'Velit ex do eiusmod pariatur nulla ea culpa sint eu. Fugiat ad officia voluptate mollit tempor deserunt irure eiusmod esse velit tempor laboris excepteur amet. Nostrud esse dolor in mollit nisi sint Lorem commodo.',
              userId: '6512f0120322c9fdf33adb85',
              isActive: false,
              created_at: '2023-09-12T08:25:23.183Z',
              profileUrl: '',
            },
            {
              id: '6512f012c96934a52d0e1d4e',
              name: 'Silvia Avila',
              text: 'Nostrud nisi ea excepteur amet minim aliquip ut nulla eiusmod sint. Deserunt aute ipsum non eu voluptate incididunt nostrud labore reprehenderit excepteur qui culpa. Eu proident pariatur esse dolore.',
              userId: '6512f012a0e251262c11d62b',
              isActive: false,
              created_at: '2023-09-04T23:48:45.530Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
            {
              id: '6512f012f263268c3e524a41',
              name: 'Pope Mays',
              text: 'Dolore nostrud est cupidatat esse labore duis ut pariatur ut consequat irure. Voluptate minim qui ut duis sunt. Ipsum enim exercitation commodo est.',
              userId: '6512f01224c1f6be021f4834',
              isActive: false,
              created_at: '2023-09-09T21:24:50.072Z',
              profileUrl: '',
            },
          ],
          created_at: '2023-09-09T11:25:01.716Z',
        },
        {
          id: '6512f0126ca1530a0a80426d',
          text: 'Exercitation officia cupidatat irure sit dolor elit labore occaecat consequat minim eiusmod consectetur amet nostrud. Irure amet nulla pariatur nisi ipsum anim aute occaecat incididunt nulla elit id exercitation. Adipisicing eu in Lorem elit occaecat cupidatat sit aute deserunt dolore nostrud. Consectetur quis tempor do ipsum cillum excepteur consequat anim.',
          comments: [
            {
              id: '6512f012afc02a313a74f72b',
              name: 'Flora Sellers',
              text: 'Veniam id esse ad sunt aliquip do Lorem officia pariatur aute culpa esse id. Officia id occaecat fugiat enim sit et sint. Enim commodo fugiat deserunt consectetur.',
              userId: '6512f012e1beac0fa6a30ed9',
              isActive: true,
              created_at: '2023-09-05T14:14:24.547Z',
              profileUrl: '',
            },
            {
              id: '6512f012a5fc3dd8885f2032',
              name: 'Adrian Ball',
              text: 'Anim sint id amet et labore. Esse duis culpa laboris nulla ut et reprehenderit consectetur nostrud dolore occaecat consectetur enim ipsum. Esse occaecat ex laborum fugiat.',
              userId: '6512f01284cf093d9968f575',
              isActive: true,
              created_at: '2023-09-04T00:06:37.456Z',
              profileUrl: '',
            },
            {
              id: '6512f012aef7e300d91b91ca',
              name: 'Rosales Sosa',
              text: 'Exercitation irure nulla adipisicing magna ullamco sunt. Voluptate ea eu ex ullamco minim nisi adipisicing incididunt laboris ex nostrud eu. Minim tempor tempor officia et ea dolor incididunt quis sint voluptate nulla.',
              userId: '6512f01201635f1df2fe3d87',
              isActive: true,
              created_at: '2023-09-15T14:36:35.265Z',
              profileUrl: '',
            },
          ],
          created_at: '2023-09-12T00:37:36.729Z',
        },
      ],
    },
    {
      id: '6512f012b2c78824608c88ca',
      text: 'Voluptate culpa labore aute enim est ipsum exercitation quis exercitation consequat nulla commodo voluptate excepteur. Minim consectetur laborum cupidatat nulla amet irure nisi consectetur do dolore sunt mollit Lorem minim. Commodo pariatur exercitation do veniam. Eiusmod tempor ad ullamco ea. Ipsum nostrud laboris incididunt reprehenderit amet non nostrud consequat nisi culpa.',
      labels: ['Negative', 'Frustration', 'Escalation Request'],
      created_at: '2023-09-05T10:39:29.750Z',
      annotations: [
        {
          id: '6512f0128c184fb23ca1f5a6',
          text: 'Enim enim proident adipisicing ea consequat consequat quis consequat. Quis eu est mollit sunt nisi minim consequat consequat tempor amet cupidatat. Aute laboris anim deserunt qui proident ex commodo Lorem occaecat. Eu ut ut ipsum culpa occaecat aute enim officia elit esse deserunt.',
          comments: [
            {
              id: '6512f0121e9adbe605aa0492',
              name: 'Rose Love',
              text: 'Velit qui sint adipisicing veniam. Aute sit et sint proident veniam aute. Nostrud enim sunt quis sint magna mollit elit laboris dolore laboris.',
              userId: '6512f0122f2f94c78696d395',
              isActive: true,
              created_at: '2023-09-05T01:47:19.670Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
            {
              id: '6512f0128d8b9806ce7ca8ae',
              name: 'Gamble Wiggins',
              text: 'Anim aute deserunt nostrud amet quis aute qui aute cupidatat Lorem officia. Minim est esse ullamco est reprehenderit. Id mollit proident excepteur fugiat exercitation ea ullamco.',
              userId: '6512f0126d1b100a911aee78',
              isActive: true,
              created_at: '2023-09-19T10:05:24.089Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
            {
              id: '6512f01260eb962e4db740e2',
              name: 'Aileen Francis',
              text: 'Excepteur commodo et deserunt deserunt culpa quis anim laborum esse non do anim. Tempor sunt elit ut magna cupidatat dolor labore excepteur minim nostrud. Occaecat laboris irure laboris aliquip excepteur labore.',
              userId: '6512f012f8280369b36413f5',
              isActive: true,
              created_at: '2023-09-21T20:03:05.539Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
          ],
          created_at: '2023-09-21T12:07:07.041Z',
        },
        {
          id: '6512f0126e9a8a6ef565323f',
          text: 'Consequat elit ea reprehenderit eiusmod cillum cillum ullamco id elit cupidatat occaecat duis. Ad reprehenderit aliqua duis laboris ex exercitation. Aliquip cupidatat incididunt proident veniam consequat labore labore exercitation esse labore ex. Ad laborum laboris ipsum ea consectetur proident elit in labore velit labore in.',
          comments: [
            {
              id: '6512f0123d8f7d44956b2150',
              name: 'Judith Baxter',
              text: 'Cupidatat excepteur eu officia exercitation dolore exercitation nulla Lorem est do commodo occaecat. Exercitation deserunt aliqua ex irure et aute consequat esse deserunt. Id laborum sit commodo ex in reprehenderit.',
              userId: '6512f012c1f3afb36cf5c8cc',
              isActive: true,
              created_at: '2023-09-04T14:51:17.010Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
            {
              id: '6512f0129f7e406018a11104',
              name: 'Watkins Reynolds',
              text: 'Cupidatat exercitation sunt in incididunt in aliqua irure. Nisi in qui exercitation eiusmod ut pariatur aliqua velit enim anim cillum consequat. Laborum in incididunt do cupidatat est nulla ea nostrud consequat incididunt.',
              userId: '6512f012101e2435f6ffcb5f',
              isActive: true,
              created_at: '2023-09-20T06:30:58.900Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
            {
              id: '6512f0125404218b29a077a6',
              name: 'Cantrell Frank',
              text: 'Aliqua occaecat in elit aute anim in amet. Irure labore ipsum dolor sint cillum elit magna pariatur incididunt dolore nulla cillum exercitation. Cillum consectetur consequat do minim cillum non.',
              userId: '6512f012f7fb53ac8b878613',
              isActive: false,
              created_at: '2023-09-19T17:52:33.836Z',
              profileUrl: '',
            },
          ],
          created_at: '2023-09-02T04:52:45.509Z',
        },
        {
          id: '6512f0128b1328a5551cdfa6',
          text: 'Nulla enim laboris nostrud proident officia nulla Lorem qui ex. Incididunt laboris amet eu dolor velit anim. Labore officia nulla dolor occaecat eiusmod. Proident ea ut id proident excepteur quis velit ad elit.',
          comments: [
            {
              id: '6512f012b5576e3fbccbf2d4',
              name: 'Jewel Duffy',
              text: 'Lorem esse laborum sint est ut consectetur qui minim in. Magna qui irure exercitation excepteur mollit sint pariatur dolore do culpa. Ut nisi amet commodo ad amet.',
              userId: '6512f0124495ebd2678b4d8b',
              isActive: false,
              created_at: '2023-09-05T13:31:44.256Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
            {
              id: '6512f012afacf3c7f0bf01be',
              name: 'Nash Foster',
              text: 'Anim nulla aliqua laboris sunt magna et id. Officia velit do aliquip ad eiusmod cupidatat dolore non culpa minim labore anim. Ex aute ex ullamco magna commodo aute amet pariatur sit magna.',
              userId: '6512f0125a39bf1648889757',
              isActive: false,
              created_at: '2023-09-08T07:10:11.266Z',
              profileUrl: '',
            },
            {
              id: '6512f012c192caf0228d4a20',
              name: 'Linda Parrish',
              text: 'Deserunt aliqua aliquip reprehenderit proident sint. Quis ullamco est non voluptate nisi. Irure nulla minim laborum mollit veniam deserunt eiusmod.',
              userId: '6512f01280601ca563b7d26f',
              isActive: true,
              created_at: '2023-09-14T19:34:35.817Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
          ],
          created_at: '2023-09-06T22:52:58.783Z',
        },
      ],
    },
    {
      id: '6512f012d151fc31b4e663c1',
      text: 'Sunt eiusmod ex ea et enim. Amet velit deserunt ea ipsum ad anim nulla elit. Eu velit eu qui aute tempor deserunt sit ut eiusmod amet in. Ad incididunt id laborum labore deserunt amet nostrud aliquip dolore nostrud ut velit. Aute consectetur qui ea qui excepteur cupidatat.',
      labels: ['Escalation Request', 'Frustration'],
      created_at: '2023-09-14T19:50:05.885Z',
      annotations: [
        {
          id: '6512f01219d61d8733365d85',
          text: 'Velit enim deserunt duis occaecat exercitation eiusmod minim proident incididunt dolor et quis id ad. Culpa dolor qui qui officia aliquip non et magna fugiat aute commodo sit ullamco ad. Labore minim fugiat qui proident eu veniam eiusmod consectetur. Officia ad tempor aute velit aliqua aute et consequat eiusmod esse velit enim magna.',
          comments: [
            {
              id: '6512f0125b9b54a51661e14a',
              name: 'Laura Valencia',
              text: 'In velit culpa nisi laborum dolore reprehenderit reprehenderit ullamco. Non ipsum incididunt velit amet nostrud. Laboris id dolor ex laboris.',
              userId: '6512f012a20bb5a1f00dc9fd',
              isActive: true,
              created_at: '2023-09-03T05:10:21.426Z',
              profileUrl: '',
            },
            {
              id: '6512f012e89a98f4d993d8cd',
              name: 'Angelita Drake',
              text: 'Dolor irure velit deserunt veniam. Amet fugiat in nostrud eu. Tempor fugiat commodo laboris nulla enim.',
              userId: '6512f0121d04e5a3428f2468',
              isActive: true,
              created_at: '2023-09-12T00:17:33.160Z',
              profileUrl: '',
            },
            {
              id: '6512f01229193c46e80033ca',
              name: 'Pacheco Gamble',
              text: 'Consequat nostrud consequat exercitation nostrud labore adipisicing in qui. Quis ex non irure sint consequat sit adipisicing eiusmod mollit exercitation voluptate. Aute esse dolor elit cupidatat culpa tempor Lorem pariatur consequat sunt.',
              userId: '6512f012719fbc2f1773b1c4',
              isActive: false,
              created_at: '2023-09-06T17:03:29.602Z',
              profileUrl: '',
            },
          ],
          created_at: '2023-09-09T05:50:14.083Z',
        },
        {
          id: '6512f01209a38bb72ceb6582',
          text: 'Nulla incididunt nisi amet magna et ea. Reprehenderit elit officia proident in et ad sunt voluptate ad. Pariatur magna labore consequat dolore labore dolor consequat irure. Magna commodo cupidatat elit nisi ad.',
          comments: [
            {
              id: '6512f0124fed74a4eede384e',
              name: 'Carly Moss',
              text: 'Adipisicing minim nulla eu minim Lorem nostrud. Deserunt irure nisi tempor adipisicing elit est. Cupidatat ea labore pariatur consectetur minim commodo non consequat.',
              userId: '6512f012e870ed4df59f94a0',
              isActive: true,
              created_at: '2023-09-16T07:30:55.639Z',
              profileUrl: '',
            },
            {
              id: '6512f012fbbd2a52857a3422',
              name: 'Reba Fleming',
              text: 'Labore voluptate labore officia duis commodo cupidatat proident officia nisi anim velit. Sunt nisi sunt voluptate velit exercitation elit laborum do occaecat consequat. Dolore laborum et sint ut laboris magna nostrud velit eu amet incididunt.',
              userId: '6512f0124ce191801d2d2b83',
              isActive: true,
              created_at: '2023-09-17T07:42:34.295Z',
              profileUrl: '',
            },
            {
              id: '6512f012fb02d543c9eeb092',
              name: 'Gay Mckinney',
              text: 'Sint irure aliqua sit nulla deserunt nisi laborum pariatur anim proident cillum cupidatat. Nulla excepteur est tempor dolore tempor anim exercitation anim sunt sit nulla mollit. Laborum adipisicing labore labore do id aute duis ex.',
              userId: '6512f01221cf6a4f290f6478',
              isActive: false,
              created_at: '2023-09-16T04:08:34.512Z',
              profileUrl: '',
            },
          ],
          created_at: '2023-09-12T10:23:34.175Z',
        },
        {
          id: '6512f012650193146d4ae406',
          text: 'Anim mollit eu incididunt pariatur eiusmod non mollit do laborum commodo. Culpa sint incididunt ut officia labore. Ex esse labore ipsum ipsum. Non quis sint enim pariatur.',
          comments: [
            {
              id: '6512f01207644bc134ac5ef3',
              name: 'Rasmussen Todd',
              text: 'Nisi ullamco exercitation commodo elit culpa exercitation dolor sunt elit incididunt. Et ea magna proident incididunt reprehenderit mollit. Id ex et deserunt enim fugiat eu sunt sit velit cillum labore commodo laboris.',
              userId: '6512f0125ad478e28bdb5a18',
              isActive: false,
              created_at: '2023-09-08T19:50:57.209Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
            {
              id: '6512f012dc413b2209d95a39',
              name: 'Dotson Weeks',
              text: 'Id ex adipisicing proident nostrud commodo nulla deserunt aliquip consequat magna do magna do. Veniam pariatur ut esse velit. Dolor ea elit sit dolore mollit ad sint.',
              userId: '6512f01293100c059811b300',
              isActive: true,
              created_at: '2023-09-12T22:11:21.384Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
            {
              id: '6512f012a259b894e6031e5e',
              name: 'Walter Mendoza',
              text: 'Velit occaecat proident laborum deserunt non duis do Lorem proident occaecat qui ea exercitation. Est mollit reprehenderit nisi Lorem pariatur dolor consectetur consequat consequat. Commodo dolor excepteur velit cillum esse officia ad minim.',
              userId: '6512f012684a69a1b67ffeda',
              isActive: false,
              created_at: '2023-09-09T07:41:30.814Z',
              profileUrl: 'https://i.pravatar.cc/300',
            },
          ],
          created_at: '2023-09-02T00:40:03.646Z',
        },
      ],
    },
  ],
};
